name: Build and publish docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gostmplcli:$(date +%s)

    - name: Publish to dockerhub registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jesusnoseq/gostmplcli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
